version: '3.7'
services:
  app:
    container_name: app
    build:
      context: app/
    networks:
      test-network:
    environment:
      MONGODB_ATLAS_URI: mongodb://mongodb:27017
    depends_on:
    - mongodb
    ports:
    - 3000:3000
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: service-catalogue
    networks:
      test-network:
    ports:
    - 27017:27017
  test:
    build:
      context: test/
    environment:
    - SERVICE_UNDER_TEST_HOSTNAME=app:3000
    entrypoint: sh -c "ls -la ./features && npm install && ./node_modules/.bin/cucumber-js ./features/**/*.feature --exit"
    networks:
      test-network:
    depends_on:
    - app
networks:
  test-network:
    driver: bridge 