name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ${{ env.RELEASE_TAG }}
        uses: actions/checkout@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: rgparkins
          password: ${{secrets.PAT}}
      - name: Run tests
        run: ./test.sh
