name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ${{ env.RELEASE_TAG }}
        uses: actions/checkout@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Run tests
        run: ./test.sh
        env:
          ACTOR: ${{github.actor}}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
